# Generated by Django 3.2.2 on 2021-08-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='products',
        ),
        migrations.AlterField(
            model_name='shops',
            name='comments',
            field=models.TextField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='shops',
            name='ratings',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
