# Generated by Django 3.2.2 on 2021-08-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210828_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shops'),
        ),
    ]
