# Generated by Django 3.2.2 on 2021-08-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210830_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
    ]
