# Generated by Django 3.2.2 on 2021-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
