# Generated by Django 3.2.2 on 2021-09-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210911_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ratings',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity_in_grams',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
