# Generated by Django 3.2.2 on 2021-09-13 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0015_auto_20210911_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratings',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.products'),
        ),
        migrations.AlterField(
            model_name='productratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity_in_grams',
            field=models.CharField(blank=True, choices=[('50grams', '50GRAMS'), ('100grams', '100GRAMS'), ('1kg', '1KG'), ('2kg', '2KG'), ('3kg', '3KG')], default='50grams', max_length=150, null=True),
        ),
    ]
