# Generated by Django 3.2.2 on 2021-09-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210913_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='products.shops'),
        ),
    ]
