# Generated by Django 3.2.2 on 2021-09-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210914_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
